# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


trigger:
- Spreads

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.0.100-preview4-010538'

  - script: dotnet test test/Spreads.Sqlite.Tests/Spreads.SQLite.Tests.csproj -f netcoreapp3.0 -c Release -v m
    displayName: 'Test Release netcoreapp3.0'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.0.100-preview4-010538'

  - script: dotnet test test/Spreads.Sqlite.Tests/Spreads.SQLite.Tests.csproj -f netcoreapp3.0 -c Release -v m
    displayName: 'Test Release netcoreapp3.0'